import { createCaseRecord, normalizeCaseRecord } from './case-record.js';
import { CaseRepository, downloadCaseBackup } from './repository.js';
import { routeMethodology } from './method-router.js';
import { composeCaseDocument } from './document.js';
import { AIPE_CRITERIA, AIPE_CATEGORIES, aipeCategoryOption } from '../methodology/aipe.js';
import { POSAS_PATIENT_ITEMS, POSAS_OBSERVER_ITEMS, buildPosasAssessmentFromGuided } from '../methodology/posas.js';

const repo = new CaseRepository();
const root = document.getElementById('app');
const state = { cases:[], current:null, step:'summary', search:'', dirty:false, saving:false };
const steps = [
  ['summary','Resumo'],['context','Objeto e contexto'],['sources','Autos e fontes'],['timeline','Cronologia'],['history','História e antecedentes'],['exam','Exame pericial'],['methods','Método e instrumentos'],['analysis','Análise médico-pericial'],['questions','Quesitos'],['conclusion','Conclusão'],['document','Documento final']
];
const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const val = v => esc(v ?? '');
const uid = p => `${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
let saveTimer;

function toast(message){ let t=document.getElementById('toast'); if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t);} t.textContent=message;t.className='toast show';setTimeout(()=>t.classList.remove('show'),2200); }
function setPath(obj,path,value){ const keys=path.split('.'); let cur=obj; keys.slice(0,-1).forEach(k=>{cur[k]??={};cur=cur[k]}); cur[keys.at(-1)]=value; }
function getPath(obj,path){ return path.split('.').reduce((o,k)=>o?.[k],obj); }
function dueClass(date){ return date && new Date(date+'T23:59:59') < new Date() ? 'due' : ''; }
function formatDate(date){ if(!date)return 'Sem prazo'; const d=new Date(date+'T12:00:00'); return Number.isNaN(d.valueOf())?date:d.toLocaleDateString('pt-BR'); }
function field(label,path,type='text',opts={}){ const value=getPath(state.current,path)??''; const attrs=`data-bind="${esc(path)}"`; if(type==='textarea') return `<div class="field ${opts.wide?'wide':''}"><label>${label}</label><textarea ${attrs} placeholder="${esc(opts.placeholder||'')}">${val(value)}</textarea>${opts.hint?`<span class="hint">${esc(opts.hint)}</span>`:''}</div>`; if(type==='select') return `<div class="field ${opts.wide?'wide':''}"><label>${label}</label><select ${attrs}>${opts.options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select></div>`; return `<div class="field ${opts.wide?'wide':''}"><label>${label}</label><input type="${type}" ${attrs} value="${val(value)}" placeholder="${esc(opts.placeholder||'')}">${opts.hint?`<span class="hint">${esc(opts.hint)}</span>`:''}</div>`; }

async function load(){ state.cases=await repo.list(); renderDashboard(); }
function shell(content,opts={}){ return `<div class="v2-shell"><header class="topbar"><button class="btn ghost mobile-menu" data-action="menu">☰</button><div class="brand">MedPer <small>V2 · local-first</small></div><div class="spacer"></div>${opts.case?`<span class="save-state">${state.saving?'Salvando…':state.dirty?'Alterações pendentes':'Salvo localmente'}</span><button class="btn ghost" data-action="dashboard">Casos</button>`:''}</header>${content}</div>`; }
function renderDashboard(){ state.current=null; const q=state.search.toLowerCase(); const cases=state.cases.filter(c=>[c.identity.title,c.identity.processNumber,c.examinedPerson.name,c.context.object].join(' ').toLowerCase().includes(q)); root.innerHTML=shell(`<main class="dashboard"><div class="dashboard-head"><div><h1>Casos periciais</h1><p>Seu trabalho médico-pericial, organizado por caso.</p></div><div class="dashboard-actions"><button class="btn" data-action="import">Importar backup</button><button class="btn primary" data-action="new-case">Novo caso</button></div></div><input class="search" id="case-search" placeholder="Buscar por caso, processo, parte ou objeto" value="${esc(state.search)}"><div style="height:18px"></div>${cases.length?`<div class="case-grid">${cases.map(caseCard).join('')}</div>`:`<div class="empty"><h2>${state.cases.length?'Nenhum caso encontrado':'Nenhum caso ainda'}</h2><p>${state.cases.length?'Tente outra busca.':'Crie o primeiro caso para iniciar o fluxo pericial.'}</p><button class="btn primary" data-action="new-case">Novo caso</button></div>`}<input id="import-file" type="file" accept="application/json" class="hidden"></main>`); bind(); }
function caseCard(c){ return `<article class="case-card" data-open-case="${esc(c.id)}"><h3>${esc(c.identity.title)}</h3><p>${esc(c.identity.processNumber||'Processo não informado')}</p><p>${esc(c.examinedPerson.name||c.context.object||'Parte/objeto ainda não informados')}</p><div class="meta-row"><span class="chip">${esc(c.identity.status)}</span><span class="chip">${esc(c.context.legalContext)}</span><span class="chip ${dueClass(c.deadlines.reportDeadline)}">${esc(formatDate(c.deadlines.reportDeadline))}</span></div></article>`; }

function newCaseModal(){ document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="case-modal"><form class="modal" id="new-case-form"><h2>Novo caso</h2><div class="grid2"><div class="field wide"><label>Título do caso</label><input name="title" required placeholder="Ex.: Souza x Hospital — dano estético"></div><div class="field"><label>Número do processo</label><input name="processNumber"></div><div class="field"><label>Tribunal / vara / origem</label><input name="court"></div><div class="field"><label>Papel profissional</label><select name="professionalRole"><option value="perita_judicial">Perita judicial</option><option value="assistente_tecnica">Assistente técnica</option><option value="parecerista">Parecerista</option><option value="outro">Outra avaliação médico-legal</option></select></div><div class="field"><label>Contexto</label><select name="context"><option value="civel">Cível</option><option value="previdenciario">Previdenciário</option><option value="securitario">Securitário</option><option value="trabalhista">Trabalhista</option><option value="responsabilidade_profissional">Responsabilidade profissional</option><option value="outro">Outro</option></select></div><div class="field"><label>Parte examinada</label><input name="examinedPerson"></div><div class="field"><label>Prazo do laudo/parecer</label><input type="date" name="reportDeadline"></div><div class="field wide"><label>Objeto pericial principal</label><textarea name="object" placeholder="Defina o que efetivamente deve ser respondido pela perícia."></textarea></div></div><div class="modal-actions"><button type="button" class="btn" data-action="close-modal">Cancelar</button><button class="btn primary">Criar caso</button></div></form></div>`); document.getElementById('new-case-form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const c=createCaseRecord(data);await repo.save(c);state.cases=await repo.list();state.current=c;state.step='summary';document.getElementById('case-modal').remove();renderWorkspace();}; bind(); }

function renderWorkspace(){ const c=state.current=normalizeCaseRecord(state.current); root.innerHTML=shell(`<div class="workspace"><aside class="sidebar" id="sidebar"><div class="case-mini"><strong>${esc(c.identity.title)}</strong><span>${esc(c.identity.processNumber||'Sem número do processo')}</span></div>${steps.map(([id,label],i)=>`<button class="step ${state.step===id?'active':''}" data-step="${id}"><i>${i+1}</i>${label}</button>`).join('')}</aside><main class="content" id="workspace">${renderStep()}</main></div>`,{case:true}); bind(); }
function heading(title,sub,actions=''){ return `<div class="section-head"><div><h1>${title}</h1><p>${sub}</p></div>${actions?`<div class="actions">${actions}</div>`:''}</div>`; }
function renderStep(){ const c=state.current; switch(state.step){
case 'summary': return `${heading('Resumo do caso','Visão operacional do processo, objeto e pendências essenciais.')}<div class="card"><div class="grid2">${field('Título','identity.title')}${field('Status','identity.status','select',{options:[['rascunho','Rascunho'],['em_analise','Em análise'],['pericia_realizada','Perícia realizada'],['aguardando_documentos','Aguardando documentos'],['concluido','Concluído'],['arquivado','Arquivado']]})}${field('Processo','identity.processNumber')}${field('Prazo','deadlines.reportDeadline','date')}${field('Parte examinada','examinedPerson.name')}${field('Data da perícia','deadlines.examinationDate','date')}${field('Objeto pericial','context.object','textarea',{wide:true})}</div></div><div class="card"><h3>Pendências do caso</h3>${pendingList(c)}</div>`;
case 'context': return `${heading('Objeto e contexto','Delimite a pergunta médico-legal antes de escolher métodos ou redigir conclusões.')}<div class="card"><div class="grid2">${field('Papel profissional','identity.professionalRole','select',{options:[['perita_judicial','Perita judicial'],['assistente_tecnica','Assistente técnica'],['parecerista','Parecerista'],['outro','Outra avaliação médico-legal']]})}${field('Contexto jurídico','context.legalContext','select',{options:[['civel','Cível'],['previdenciario','Previdenciário'],['securitario','Securitário'],['trabalhista','Trabalhista'],['responsabilidade_profissional','Responsabilidade profissional'],['outro','Outro']]})}${field('Tribunal / vara / origem','identity.court')}${field('Especialidade clínica relevante','context.specialty')}${field('Objeto pericial','context.object','textarea',{wide:true})}${field('Questão médico-legal central','analysis.medicoLegalQuestion','textarea',{wide:true,placeholder:'Qual é a pergunta técnica que precisa ser respondida?'})}</div></div>`;
case 'sources': return `${heading('Autos e fontes','Cadastre o material efetivamente considerado e deixe sua origem rastreável.',`<button class="btn primary" data-action="add-source">Adicionar fonte</button>`)}<div class="list">${c.sources.length?c.sources.map(sourceItem).join(''):'<div class="empty">Nenhuma fonte cadastrada.</div>'}</div>`;
case 'timeline': return `${heading('Cronologia','Transforme documentos dispersos em uma sequência factual verificável.',`<button class="btn primary" data-action="add-event">Adicionar evento</button>`)}<div class="list">${c.timeline.length?c.timeline.sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map(eventItem).join(''):'<div class="empty">Nenhum evento cronológico cadastrado.</div>'}</div>`;
case 'history': return `${heading('História e antecedentes','Registre apenas elementos pertinentes ao objeto da perícia.')}<div class="card"><div class="grid2">${field('Síntese da história','history.summary','textarea',{wide:true})}${field('Antecedentes relevantes','history.antecedents','textarea')}${field('Tratamentos / evolução','history.treatments','textarea')}${field('Queixas atuais','history.complaints','textarea')}${field('Limitações referidas','history.limitations','textarea')}</div></div>`;
case 'exam': return `${heading('Exame pericial','Achados objetivos, negativos pertinentes, mensurações e limitações do exame.')}<div class="card"><div class="grid2">${field('Síntese do exame','examination.summary','textarea',{wide:true})}${field('Achados positivos','examination.positives','textarea')}${field('Achados negativos pertinentes','examination.negatives','textarea')}${field('Mensurações','examination.measurements','textarea')}${field('Limitações do exame','examination.limitations','textarea')}${field('Documentação fotográfica','examination.photographs','textarea',{wide:true,placeholder:'Descreva fotografias produzidas, identificação e condições.'})}</div></div>`;
case 'methods': return methodsStep();
case 'analysis': return analysisStep();
case 'questions': return `${heading('Quesitos','Responda de forma técnica, objetiva e coerente com a fundamentação.',`<button class="btn primary" data-action="add-question">Adicionar quesito</button>`)}<div class="list">${c.questions.length?c.questions.map(questionItem).join(''):'<div class="empty">Nenhum quesito cadastrado.</div>'}</div>`;
case 'conclusion': return `${heading('Conclusão','Síntese médico-legal final. O MedPer não decide por você.')}<div class="notice">A conclusão deve refletir sua análise e os limites do objeto pericial; o sistema não atribui certeza ou nexo automaticamente.</div><div class="card"><div class="grid2">${field('Conclusão principal','conclusion.summary','textarea',{wide:true})}${field('Nexo causal','conclusion.nexus','textarea')}${field('Incapacidade','conclusion.incapacity','textarea')}${field('Dano estético','conclusion.aestheticDamage','textarea')}${field('Dano funcional','conclusion.functionalDamage','textarea')}${field('Prognóstico','conclusion.prognosis','textarea')}</div></div>`;
case 'document': return documentStep(); default:return '';} }
function pendingList(c){ const p=[]; if(!c.context.object)p.push('Objeto pericial não delimitado'); if(!c.sources.length)p.push('Nenhuma fonte/autos cadastrados'); if(!c.history.summary)p.push('História ainda não sintetizada'); if(!c.examination.summary)p.push('Exame pericial ainda não registrado'); if(!c.analysis.reasoning)p.push('Fundamentação médico-pericial ainda não registrada'); if(!c.conclusion.summary)p.push('Conclusão ainda não registrada'); return p.length?`<ul>${p.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p>Nenhuma pendência estrutural essencial identificada.</p>'; }
function sourceItem(s){ return `<div class="list-item"><div class="grow"><strong>${esc(s.title||s.type)}</strong><div><small>${esc([s.type,s.date,s.origin].filter(Boolean).join(' · '))}</small></div>${s.notes?`<p>${esc(s.notes)}</p>`:''}</div><button class="btn danger" data-remove-source="${s.id}">Excluir</button></div>`; }
function eventItem(e){ return `<div class="list-item"><div class="grow"><strong>${esc(e.date||'Sem data')} · ${esc(e.title)}</strong><div><small>${esc(e.certainty||'')}</small></div>${e.description?`<p>${esc(e.description)}</p>`:''}</div><button class="btn danger" data-remove-event="${e.id}">Excluir</button></div>`; }
function questionItem(q,i){ return `<div class="card"><div class="field"><label>Quesito ${i+1}</label><textarea data-list-bind="questions" data-id="${q.id}" data-key="question">${val(q.question)}</textarea></div><div class="field"><label>Resposta</label><textarea data-list-bind="questions" data-id="${q.id}" data-key="answer">${val(q.answer)}</textarea></div><div style="margin-top:8px"><button class="btn danger" data-remove-question="${q.id}">Excluir</button></div></div>`; }
function methodsStep(){ const c=state.current; const routes=routeMethodology(c); return `${heading('Método e instrumentos','O MedPer sugere instrumentos conforme o objeto; você decide o que efetivamente se aplica.')}<div class="notice">Sugestão contextual não equivale a conclusão pericial. Métodos devem ser aplicados conforme indicação, limitações e documentação disponível.</div><div class="method-grid">${routes.length?routes.map(r=>`<div class="method-card"><strong>${esc(r.label)}</strong><p>${esc(r.description)}</p></div>`).join(''):'<div class="method-card"><strong>Nenhum instrumento específico sugerido</strong><p>Refine o objeto ou registre metodologia livre abaixo.</p></div>'}</div>${routes.some(r=>r.id==='aipe')?aipeBlock():''}${routes.some(r=>r.id==='posas')?posasBlock():''}<div class="card"><h3>Notas metodológicas</h3>${field('Método, referências e limitações','methodology.notes','textarea',{wide:true})}</div>`; }
function aipeBlock(){ const guided=state.current.methodology.aipe||{}; return `<div class="card"><h3>AIPE — registro estruturado</h3><p class="hint">Os cinco eixos ajudam a estruturar percepção e impacto. A graduação final permanece decisão da perita.</p>${AIPE_CRITERIA.map(c=>`<div class="aipe-row"><div><strong>${esc(c.label)}</strong><div class="hint">${esc(c.question)}</div></div><select data-method="aipe" data-key="${c.field}"><option value="">Não avaliado</option>${c.options.map(o=>`<option ${guided[c.field]===o?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`).join('')}<div class="grid2"><div class="field"><label>Categoria AIPE</label><select data-method="aipe" data-key="category"><option value="">Não definida</option>${AIPE_CATEGORIES.map(c=>`<option value="${c.id}" ${guided.category===c.id?'selected':''}>${esc(aipeCategoryOption(c))}</option>`).join('')}</select></div><div class="field"><label>Pontuação final (decisão pericial)</label><input class="score" type="number" min="0" max="50" data-method="aipe" data-key="score" value="${val(guided.score||'')}"></div></div></div>`; }
function posasBlock(){ const g=state.current.methodology.posas||{}; const rows=(items,prefix)=>items.map(it=>`<div class="posas-row"><span>${esc(it.label)}</span><input class="score" type="number" min="1" max="10" data-method="posas" data-key="${prefix}_${it.id}" value="${val(g[`${prefix}_${it.id}`]||'')}"></div>`).join(''); const assessed=buildPosasAssessmentFromGuided(g); return `<div class="card"><h3>POSAS 2.0</h3><div class="grid2">${simpleMethodField('Área avaliada','posas','posasArea',g.posasArea)}${simpleMethodField('Critério de seleção','posas','posasSelectionCriterion',g.posasSelectionCriterion)}</div><h4>Paciente</h4>${rows(POSAS_PATIENT_ITEMS,'posasPatient')}<h4>Observador</h4>${rows(POSAS_OBSERVER_ITEMS,'posasObserver')}<p class="hint">Totais: paciente ${assessed.patient.total??'incompleto'} · observador ${assessed.observer.total??'incompleto'}. As escalas permanecem independentes.</p></div>`; }
function simpleMethodField(label,method,key,value){ return `<div class="field"><label>${label}</label><input data-method="${method}" data-key="${key}" value="${val(value||'')}"></div>`; }
function analysisStep(){ const c=state.current; return `${heading('Análise médico-pericial','Construa a cadeia explícita entre fontes, achados, interpretações e conclusão.',`<button class="btn" data-action="add-claim">Adicionar vínculo de evidência</button>`)}<div class="card"><div class="matrix">${field('Questão médico-legal','analysis.medicoLegalQuestion','textarea')}${field('Evidências favoráveis','analysis.favorable','textarea')}${field('Evidências contrárias','analysis.contrary','textarea')}${field('Estado anterior','analysis.priorState','textarea')}${field('Alternativas / concausas','analysis.alternatives','textarea')}${field('Limitações','analysis.limitations','textarea')}${field('Fundamentação técnico-pericial','analysis.reasoning','textarea',{wide:true})}</div></div>${c.evidenceClaims.length?`<div class="card"><h3>Matriz de evidências</h3>${c.evidenceClaims.map(cl=>`<div class="evidence-chain">${esc(cl.statement||'fato')} → ${esc(cl.finding||'achado')} → ${esc(cl.interpretation||'interpretação')} → ${esc(cl.impact||'impacto')} <button class="btn danger" data-remove-claim="${cl.id}">Excluir</button></div>`).join('<div style="height:8px"></div>')}</div>`:''}`; }
function documentStep(){ const c=state.current; return `${heading('Documento final','O documento é composto com o conteúdo que você registrou — sem preencher lacunas por conta própria.',`<button class="btn" data-action="backup">Backup JSON</button><button class="btn primary" data-action="print">Abrir para imprimir / PDF</button>`)}<div class="card"><div class="grid2">${field('Título do documento','document.title')}${field('Assinatura / identificação profissional','document.signature')}${field('Introdução','document.introduction','textarea',{wide:true})}${field('Discussão complementar','document.discussion','textarea',{wide:true})}</div></div><div class="doc-preview"><h3>Prévia estrutural</h3><p><strong>${esc(c.document.title||'Laudo médico-pericial')}</strong></p><p>${esc(c.identity.title)}</p><p>${esc(c.context.object)}</p><hr><p>${esc(c.conclusion.summary||'A conclusão ainda não foi preenchida.')}</p></div><p class="footer-note">Use “Abrir para imprimir / PDF” para gerar uma versão A4 em nova janela e salvar pelo diálogo de impressão do navegador.</p>`; }

function bind(){
  root.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{state.step=b.dataset.step;renderWorkspace();});
  root.querySelectorAll('[data-open-case]').forEach(el=>el.onclick=async()=>{state.current=await repo.get(el.dataset.openCase);state.step='summary';renderWorkspace();});
  root.querySelectorAll('[data-bind]').forEach(el=>el.oninput=()=>{setPath(state.current,el.dataset.bind,el.value);scheduleSave();});
  root.querySelectorAll('[data-list-bind]').forEach(el=>el.oninput=()=>{const item=state.current[el.dataset.listBind].find(x=>x.id===el.dataset.id);if(item){item[el.dataset.key]=el.value;scheduleSave();}});
  root.querySelectorAll('[data-method]').forEach(el=>el.oninput=()=>{state.current.methodology[el.dataset.method]??={};state.current.methodology[el.dataset.method][el.dataset.key]=el.value;scheduleSave();});
  const search=root.querySelector('#case-search'); if(search) search.oninput=e=>{state.search=e.target.value;renderDashboard();};
  root.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=e=>handleAction(e,btn.dataset.action));
  root.querySelectorAll('[data-remove-source]').forEach(b=>b.onclick=()=>{state.current.sources=state.current.sources.filter(x=>x.id!==b.dataset.removeSource);saveNow(true);renderWorkspace();});
  root.querySelectorAll('[data-remove-event]').forEach(b=>b.onclick=()=>{state.current.timeline=state.current.timeline.filter(x=>x.id!==b.dataset.removeEvent);saveNow(true);renderWorkspace();});
  root.querySelectorAll('[data-remove-question]').forEach(b=>b.onclick=()=>{state.current.questions=state.current.questions.filter(x=>x.id!==b.dataset.removeQuestion);saveNow(true);renderWorkspace();});
  root.querySelectorAll('[data-remove-claim]').forEach(b=>b.onclick=()=>{state.current.evidenceClaims=state.current.evidenceClaims.filter(x=>x.id!==b.dataset.removeClaim);saveNow(true);renderWorkspace();});
}
async function handleAction(e,action){ e?.preventDefault();
  if(action==='new-case')return newCaseModal(); if(action==='close-modal')return document.getElementById('case-modal')?.remove(); if(action==='dashboard'){await saveNow();state.cases=await repo.list();return renderDashboard();}
  if(action==='menu')return document.getElementById('sidebar')?.classList.toggle('open');
  if(action==='import'){const input=document.getElementById('import-file'); input.click(); input.onchange=async()=>{try{const text=await input.files[0].text();await repo.import(text);state.cases=await repo.list();renderDashboard();toast('Backup importado.');}catch(err){toast(err.message||'Falha ao importar.');}};return;}
  if(action==='add-source')return editModal('Nova fonte',[['type','Tipo','select',[['documento_autos','Documento dos autos'],['prontuario','Prontuário'],['laudo_previo','Laudo prévio'],['imagem','Imagem/fotografia'],['relato','Relato da parte'],['exame','Exame complementar'],['literatura','Literatura/norma']]],['title','Título'],['date','Data','date'],['origin','Origem'],['notes','Observações','textarea']],data=>{state.current.sources.push({id:uid('src'),...data});saveNow(true);renderWorkspace();});
  if(action==='add-event')return editModal('Novo evento cronológico',[['date','Data','date'],['title','Título'],['description','Descrição factual','textarea'],['certainty','Grau de certeza','select',[['documentado','Documentado'],['compativel','Compatível'],['provavel','Provável'],['possivel','Possível'],['nao_sustentado','Não sustentado']]]],data=>{state.current.timeline.push({id:uid('evt'),sourceIds:[],...data});saveNow(true);renderWorkspace();});
  if(action==='add-question'){state.current.questions.push({id:uid('q'),question:'',answer:''});await saveNow(true);return renderWorkspace();}
  if(action==='add-claim')return editModal('Vínculo de evidência',[['statement','Fato documentado','textarea'],['finding','Achado','textarea'],['interpretation','Interpretação','textarea'],['impact','Impacto na conclusão','textarea'],['limitations','Limitações','textarea'],['confidence','Grau de certeza','select',[['documentado','Documentado'],['compativel','Compatível'],['provavel','Provável'],['possivel','Possível'],['nao_sustentado','Não sustentado']]]],data=>{state.current.evidenceClaims.push({id:uid('claim'),sourceIds:[],...data});saveNow(true);renderWorkspace();});
  if(action==='backup')return downloadCaseBackup(state.current);
  if(action==='print'){await saveNow();const w=window.open('','_blank');if(!w){toast('O navegador bloqueou a nova janela.');return;}w.document.write(composeCaseDocument(state.current));w.document.close();return;}
}
function editModal(title,fields,onSave){ document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="edit-modal"><form class="modal" id="edit-form"><h2>${esc(title)}</h2><div class="grid2">${fields.map(([name,label,type='text',options])=>{if(type==='textarea')return `<div class="field wide"><label>${label}</label><textarea name="${name}"></textarea></div>`;if(type==='select')return `<div class="field"><label>${label}</label><select name="${name}">${options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></div>`;return `<div class="field"><label>${label}</label><input name="${name}" type="${type}"></div>`}).join('')}</div><div class="modal-actions"><button type="button" class="btn" id="edit-cancel">Cancelar</button><button class="btn primary">Salvar</button></div></form></div>`); document.getElementById('edit-cancel').onclick=()=>document.getElementById('edit-modal').remove();document.getElementById('edit-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));document.getElementById('edit-modal').remove();onSave(data);}; }
function scheduleSave(){ state.dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveNow(),500); updateSaveLabel(); }
function updateSaveLabel(){ const el=root.querySelector('.save-state'); if(el) el.textContent=state.saving?'Salvando…':state.dirty?'Alterações pendentes':'Salvo localmente'; }
async function saveNow(silent=false){ if(!state.current)return;clearTimeout(saveTimer);state.saving=true;updateSaveLabel();state.current=await repo.save(state.current);state.dirty=false;state.saving=false;updateSaveLabel();if(!silent){} }
window.addEventListener('beforeunload',()=>{ if(state.current&&state.dirty) repo.save(state.current); });
load().catch(err=>{console.error(err);root.innerHTML=`<div class="dashboard"><div class="empty"><h2>Não foi possível iniciar o MedPer</h2><p>${esc(err.message)}</p></div></div>`;});
